### ISSUE TITLE
Error when trying to use Facebook authentication from step 17

### ISSUE THREAD

**Issue by santteegt** [Urigo/Ionic2CLI-Meteor-WhatsApp#101]
Hi, 

I have followed the instructions from step 17.1 to 17.7 in order to test the facebook login functionality, but I'm getting the following error after entering the user credentials and clicking on the login button in the facebook login page:

```
Error in OAuth Server: redirectUrl (http://192.168.2.15/) is not on the same host as the app (http://192.168.2.15:3000/)
```

I'm running the ionic app on `http://192.168.2.15:8100`, whereas the meteor server on `http://192.168.2.15:3000`. 

My `meteor-client.config.json` is configured as follows:

```
{
  "runtime": {
    "DDP_DEFAULT_CONNECTION_URL": "http://192.168.2.15",
    "ROOT_URL": "http://192.168.2.15"
  },
  "import": [

  ]
}
```
Finally, in my `nginx.config` configuration file, the proxy is configured as follows:

```
server {
            listen      80;
            server_name 192.168.2.15;

            location / {
                proxy_pass http://192.168.2.15:8100;
            }
            location ~ ^/(_oauth|packages|ufs) {
                proxy_pass http://192.168.2.15:3000;
            }
            location /sockjs {
                proxy_pass http://192.168.2.15:3000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
           }
            error_page  500 502 503 504 /50x.html;

            location = /50x.html {
                root /usr/share/ngix/html;
            }
        }
```

Hope you can help me with some hints on how to solve that.

Regards

**Comment by darkbasic** [comment]
Which url did you type in the browser to reach the app? It must be port 80.

**Comment by santteegt** [comment]
Hi,

Yes.  To access to my app I use `http://192.168.2.15`

**Comment by darkbasic** [comment]
Maybe some Facebook app setting... Can you please post a screenshot? Here is mine: 
![facebook_meteor_app](https://user-images.githubusercontent.com/1047358/27354485-095aea1a-5608-11e7-9eb5-0dacb556e1a9.png)
Some settings are probably outdated, but you can try to mimic mine.

**Comment by darkbasic** [comment]
Also please check if the fb login works for you as is in the tutorial (with my fb app id, etc..).

The following is the correct procedure to check out the tutorial from the git repo. You will have to open 2 shells (3 if you want to test it on Android).

Shell 1:
$ git clone https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp.git
$ cd Ionic2CLI-Meteor-WhatsApp/
$ npm install
$ npm uninstall sharp
$ meteor npm install sharp
$ npm run api

shell1 log

Shell 2:
$ npm run meteor-client:bundle
$ npm run ionic:serve

shell2 log

Shell 3 (Android testing):
$ cordova platform add android
$ cordova run android

shell3 log

Check your `npm list -g --depth=0` and your `npm outdated -g` because you will need fresh packages.

**Comment by santteegt** [comment]
Hi,

I finally solved the issue by developing the server side of my app on a linux machine which is easier to open port 80. Previously, I was testing this on a docker container running on my Macbook Pro where it is not that easy to open port 80.

**Comment by darkbasic** [comment]
I'm glad to hear that you solved your problem with the Facebook auth!

**Comment by paduchurikowsik** [comment]
hello @darkbasic , i am using "mup"  for deploying my sever on ubuntu machine which uses docker. how should i go config the Nginx in this case. 

The other thing is meteor application has both client and server code, and a mobile app connecting the server. The problem is that if we the "Nginx" config you gave then wouldn't it bypass the meteor app's client loginwithfacebook ??? if it would how should we config the Nginx

here is the structure of application

Meteor app has
server and client

ionic+meteor 
client with DDL connection link to the website
