### ISSUE TITLE
Tutorial Problem Chap 8 when npm run api

### ISSUE THREAD

**Issue by badbytes1** [Urigo/Ionic2CLI-Meteor-WhatsApp#128]
Hello i try to follow the tutorial to build the chat but i get stuck when i try to launch the meteor server with npm run api.
Here is the error from the windows shell:
![bug](https://user-images.githubusercontent.com/31258986/29691334-ef0c2e8e-892a-11e7-8e54-a1b9832714db.PNG)
i tried to remake symlink with the bash version for windows.
it seems good.
![bug2](https://user-images.githubusercontent.com/31258986/29691390-26f4f9d4-892b-11e7-9e9d-e92a5002509b.PNG)

Thanks for your help! i really need it, i try to accomplish my Bachelor thesis

**Comment by pkitatta** [comment]
try `meteor`

**Comment by darkbasic** [comment]
I hardcoded Linux-compatible scripts into package.json, I didn't take Windows into account. Just run `meteor run --settings private\settings.json` from the API directory. Please change the syntax according to your OS (I think it should use `\` instead of `/`, but I'm not sure). I'm closing, feel free to reopen if the issue persists.
