### ISSUE TITLE
autoScroller does not work

### ISSUE THREAD

**Issue by gotu** [Urigo/Ionic2CLI-Meteor-WhatsApp#21]
https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/blob/master/src/pages/messages/messages.ts#L84

```    
this.autoScroller = MeteorObservable.autorun().subscribe(() => {
      this.scroller.scrollTop = this.scroller.scrollHeight;
      this.messageEditor.focus();
});
```
this does not work. I'm new to RxJS and the meteor-rxjs layer, so I can't tell what is going on here now.
As I see it, there is no bug in setting the scrollTop itself, it' the right dom element. But it (the handler) does not get called (or not in the right context or maybe zone) as it should on every "change".

**Comment by DAB0mB** [comment]
@gotu Thank you for submitting this issue. I just fixed it, as can be seen here: https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/blob/master/manuals/views/step4.md. The problem was that we used an observable instead of a mutation observer. The names might sound similar, but their roles are completely different. I'm closing this issue, and I will make sure to update the Meteor CLI version as well :-)
